vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        poster_file:
            uri_prefix: /uploads/images/posters
            upload_destination: '%upload_directory%/posters'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        avatar_file:
            uri_prefix: /uploads/images/avatar
            upload_destination: '%upload_directory%/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
